/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoadRawDialog.java
 *
 * Created on Aug 2, 2010, 11:02:10 PM
 */

package edu.ohio.graphcuts.gui.diag;

import java.io.File;
import javax.swing.JFileChooser;

/**
 * File selection and image dimension dialog for selecting
 * medical images in RAW format (grayscale, byte value equals intensity).
 * @author david
 */
public class LoadRawDialog extends javax.swing.JDialog {

    private int imageWidth;
    private int imageHeight;
    private boolean cancelled = true;

    /** Creates new form LoadRawDialog */
    public LoadRawDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public String getSelectedFile() {
        return fileField.getText();
    }

    public int getImageWidth() {
        return imageWidth;
    }

    public int getImageHeight() {
        return imageHeight;
    }

    public boolean isCancelled() {
        return cancelled;
    }

    private void setImageDimensions() {
        imageWidth = Integer.parseInt(widthField.getText());
        imageHeight = Integer.parseInt(heightField.getText());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fileField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        widthField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        heightField = new javax.swing.JTextField();
        bottomPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Load RAW Image");

        centerPanel.setLayout(new java.awt.GridLayout(0, 3));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("File:  ");
        centerPanel.add(jLabel1);
        centerPanel.add(fileField);

        jButton1.setText("Select File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        centerPanel.add(jButton1);
        centerPanel.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Image Width:");
        centerPanel.add(jLabel3);

        widthField.setText("256");
        centerPanel.add(widthField);
        centerPanel.add(jLabel4);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Image Height:");
        centerPanel.add(jLabel5);

        heightField.setText("256");
        centerPanel.add(heightField);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.GridLayout(0, 1));

        buttonPanel.setLayout(new java.awt.GridLayout());

        okButton.setText("Load Image");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        bottomPanel.add(buttonPanel);

        statusLabel.setText("Status:");
        statusLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        bottomPanel.add(statusLabel);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser jfc = new JFileChooser();
        int retVal = jfc.showOpenDialog(this);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            File selFile = jfc.getSelectedFile();
            fileField.setText(selFile.getAbsolutePath());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try {
            setImageDimensions();
            cancelled = false;
            dispose();
        } catch (Exception e) {
            statusLabel.setText("Check width and height values.");
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancelled = true;
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoadRawDialog dialog = new LoadRawDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                dialog.setModal(true);
                if (!dialog.isCancelled()) {
                    System.out.println("Selected "+dialog.getSelectedFile());
                    System.out.println("Image width set at "+dialog.getImageWidth());
                    System.out.println("Image height set at "+dialog.getImageHeight());
                } else {
                    System.out.println("Dialog was cancelled!");
                }
                System.exit(0);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JTextField fileField;
    private javax.swing.JTextField heightField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField widthField;
    // End of variables declaration//GEN-END:variables

}
