/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SegTreePanel.java
 *
 * Created on Aug 3, 2010, 9:04:35 PM
 */

package edu.ohio.graphcuts.gui.panel;

import edu.ohio.graphcuts.gui.tree.CutImage;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;

/**
 *
 * @author david
 */
public class SegTreePanel extends javax.swing.JPanel {

    /** Creates new form SegTreePanel */
    public SegTreePanel() {
        initComponents();
    }

    public void setRootImage(String imgFile) {
        CutImage rootSet = new CutImage(imgFile);
        DefaultMutableTreeNode root = new DefaultMutableTreeNode(rootSet,true);
        tree.setModel(new DefaultTreeModel(root));
    }

    public JTree getTree() {
        return tree;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Segmentation Tree"));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(tree);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables

}
