/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImageInfoPanel.java
 *
 * Created on Aug 1, 2010, 8:38:20 PM
 */

package gcgui.panel;

import edu.ohio.graphcuts.analysis.Entropy;
import edu.ohio.graphcuts.analysis.Histogram;
import java.awt.image.BufferedImage;
import java.util.Vector;

/**
 *
 * @author david
 */
public class ImageInfoPanel extends javax.swing.JPanel {

    private Vector<String> items;

    /** Creates new form ImageInfoPanel */
    public ImageInfoPanel() {
        initComponents();
        clearList();
    }

    public void addItem(String item) {
        items.add(item);
        list.setListData(items);
    }

    public Vector<String> getItems() {
        return items;
    }

    public void setItems(Vector<String> items) {
        this.items = items;
        list.setListData(items);
    }

    public void clearList() {
        items = new Vector<String>();
        list.setListData(items);
    }

    public void showInfo(BufferedImage img) {
        clearList();
        String[] props = img.getPropertyNames();
        if (props != null) {
            for (int i=0;i<props.length;i++) {
                if (props[i] != null) {
                    String line = props[i] + " = "+img.getProperty(props[i]);
                    addItem(line);
                }
            }
        }
        Histogram hist = new Histogram(img);
        Entropy entropy = new Entropy();
        String ent = "Gray-scale entropy = "+Double.toString(entropy.getValueEntropy(hist));
        addItem(ent);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Image Information"));
        setLayout(new java.awt.BorderLayout());

        list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list;
    // End of variables declaration//GEN-END:variables

}
