/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProgressPanel.java
 *
 * Created on Jan 20, 2011, 2:31:02 PM
 */

package gcgui.panel;

import edu.ohio.graphcuts.alg.bradbury.ImageConsumer;
import java.awt.image.BufferedImage;

/**
 *
 * @author David Days <david.c.days@gmail.com>
 */
public class ProgressPanel extends javax.swing.JPanel implements ImageConsumer {

    private TitledImagePane labelPane;
    private TitledImagePane slinkPane;
    private TitledImagePane tlinkPane;
    private TitledImagePane cutPane;
    private TitledLayeredImagePane pathPane;
    private int src;
    private int sink;

    /** Creates new form ProgressPanel */
    public ProgressPanel(int src, int sink, BufferedImage oimg) {
        this.src = src;
        this.sink = sink;
        initComponents();
        //instantiate the panels
        labelPane = new TitledImagePane("Labeling");
        slinkPane = new TitledImagePane("S-Links");
        tlinkPane = new TitledImagePane("T-Links");
        cutPane = new TitledImagePane("Cuts");
        pathPane = new TitledLayeredImagePane("Current Path");
        pathPane.setBackgroundImage(oimg);

        //Add to the layout
        add(labelPane);
        add(slinkPane);
        add(tlinkPane);
        add(cutPane);
        add(pathPane);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(0, 2));
    }// </editor-fold>//GEN-END:initComponents

    public void pathImage(String title, BufferedImage img) {
        pathPane.setForegroundImageTitle(img, title);
    }

    public void labelImage(String title, BufferedImage img) {
        labelPane.setImageCaption(img, title);
    }

    public void tlinkImage(String title, BufferedImage img, int label) {
        if (label == src) {
            slinkPane.setImageCaption(img, title);
        } else if (label == sink) {
            tlinkPane.setImageCaption(img, title);
        }
        
    }

    public void cutImage(String title, BufferedImage img) {
        cutPane.setImageCaption(img, title);
    }

    public void pathImage(int iteration, BufferedImage img) {
        //not implemented
    }

    public void labelImage(int iteration, BufferedImage img) {
        //not implemented
    }

    public void tlinkImage(int iteration, BufferedImage img, int label) {
        //not implemented
    }

    public void cutImage(int iteration, BufferedImage img) {
        //not implemented
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
