/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TitledImagePane.java
 *
 * Created on Jan 20, 2011, 2:00:43 PM
 */

package gcgui.panel;

import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import javax.swing.border.TitledBorder;

/**
 *
 * @author David Days <david.c.days@gmail.com>
 */
public class TitledImagePane extends javax.swing.JPanel {

    private ImagePanel ipanel;

    /** Creates new form TitledImagePane */
    public TitledImagePane(String t) {
        initComponents();
        ipanel = new ImagePanel();
        add(ipanel, BorderLayout.CENTER);
        ((TitledBorder)getBorder()).setTitle(t);
    }

    public void setImageCaption(BufferedImage img, String ctext) {
        ipanel.setImage(img);
        caption.setText(ctext);
    }

    public BufferedImage getImage() {
        return ipanel.getImage();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caption = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("paneltitle"));
        setLayout(new java.awt.BorderLayout());

        caption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caption.setText(" ");
        caption.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(caption, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caption;
    // End of variables declaration//GEN-END:variables

}
