/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Selector.java
 *
 * Created on Nov 16, 2010, 1:13:28 PM
 */

package gcgui;

import gcgui.frame.NLabelBorderCutFrame;
import gcgui.frame.ProgressCutFrame;
import gcgui.frame.STBKCutFrame;
import gcgui.frame.STBorderCutFrame;
import gcgui.frame.STUFBorderCutFrame;
import gcgui.frame.UGHSVKFrame;
import gcgui.frame.UserGuidedFrame;
import gcgui.frame.XYIBKCutFrame;
import gcgui.frame.XYIBorderCutFrame;

/**
 *
 * @author david
 */
public class Selector extends javax.swing.JFrame {

    /** Creates new form Selector */
    public Selector() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stbkButton = new javax.swing.JButton();
        stborderButton = new javax.swing.JButton();
        stufborderButton = new javax.swing.JButton();
        xyistbkButton = new javax.swing.JButton();
        xyistborderButton = new javax.swing.JButton();
        intlabelbcButton = new javax.swing.JButton();
        progressButton = new javax.swing.JButton();
        userNLabelButton = new javax.swing.JButton();
        ughsvkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graph-Cut Analysis Interface");
        getContentPane().setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        stbkButton.setText("Intensity S-T using BK Tree Cut");
        stbkButton.setToolTipText("Use the BK Tree Cut Algorithm to perform a two-part segmentation on an image according to intensity only.");
        stbkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stbkButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stbkButton);

        stborderButton.setText("Intensity S-T using Border Cut");
        stborderButton.setToolTipText("Use the Border Cut algorithm to conduct two-label segmentation on an image using intensity only.");
        stborderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stborderButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stborderButton);

        stufborderButton.setText("Intensity S-T using UnionFind Border Cut");
        stufborderButton.setToolTipText("Use the UnionFind implementation of the Border Cut algorithm to conduct two-label segmentation on an image using intensity only.");
        stufborderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stufborderButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stufborderButton);

        xyistbkButton.setText("Intensity and Location S-T using BK Tree Cut");
        xyistbkButton.setToolTipText("Use the BK Tree Cut Algorithm to perform a two-part segmentation on an image according to intensity and position.");
        xyistbkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xyistbkButtonActionPerformed(evt);
            }
        });
        getContentPane().add(xyistbkButton);

        xyistborderButton.setText("Intensity and Location S-T using Border Cut");
        xyistborderButton.setToolTipText("Use the Border Cut algorithm to conduct two-label segmentation on an image using intensity and location.");
        xyistborderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xyistborderButtonActionPerformed(evt);
            }
        });
        getContentPane().add(xyistborderButton);

        intlabelbcButton.setText("Intensity Only N-Label Border Cut");
        intlabelbcButton.setToolTipText("Use the UnionFind implementation of the Border Cut algorithm to conduct two-label segmentation on an image using intensity only.");
        intlabelbcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intlabelbcButtonActionPerformed(evt);
            }
        });
        getContentPane().add(intlabelbcButton);

        progressButton.setText("Illustrated Graph-Cuts");
        progressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressButtonActionPerformed(evt);
            }
        });
        getContentPane().add(progressButton);

        userNLabelButton.setText("User-Guided N-Label BorderCut");
        userNLabelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNLabelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(userNLabelButton);

        ughsvkButton.setText("User-Guided and K-Means Smoothed Color BorderCut");
        ughsvkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ughsvkButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ughsvkButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stbkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stbkButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STBKCutFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_stbkButtonActionPerformed

    private void stborderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stborderButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STBorderCutFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_stborderButtonActionPerformed

    private void xyistbkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xyistbkButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XYIBKCutFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_xyistbkButtonActionPerformed

    private void xyistborderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xyistborderButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XYIBorderCutFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_xyistborderButtonActionPerformed

    private void stufborderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stufborderButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STUFBorderCutFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_stufborderButtonActionPerformed

    private void intlabelbcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intlabelbcButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NLabelBorderCutFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_intlabelbcButtonActionPerformed

    private void progressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgressCutFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_progressButtonActionPerformed

    private void userNLabelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNLabelButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserGuidedFrame ugf = new UserGuidedFrame();
                ugf.setSize(600,600);
                ugf.setVisible(true);
            }
        });
    }//GEN-LAST:event_userNLabelButtonActionPerformed

    private void ughsvkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ughsvkButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UGHSVKFrame ughsvf = new UGHSVKFrame();
                ughsvf.setSize(600,600);
                ughsvf.setVisible(true);
            }
        });
    }//GEN-LAST:event_ughsvkButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton intlabelbcButton;
    private javax.swing.JButton progressButton;
    private javax.swing.JButton stbkButton;
    private javax.swing.JButton stborderButton;
    private javax.swing.JButton stufborderButton;
    private javax.swing.JButton ughsvkButton;
    private javax.swing.JButton userNLabelButton;
    private javax.swing.JButton xyistbkButton;
    private javax.swing.JButton xyistborderButton;
    // End of variables declaration//GEN-END:variables

}
