/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SampleSetListPanel.java
 *
 * Created on Mar 14, 2011, 12:40:52 AM
 */

package gcgui.widgets;

import gcgui.data.Sample;
import gcgui.data.SampleSet;

/**
 *
 * @author David Days <david.c.days@gmail.com>
 */
public class SampleSetListPanel extends javax.swing.JPanel {

    private SampleSet sset;

    /** Creates new form SampleSetListPanel */
    public SampleSetListPanel() {
        initComponents();
    }

    public void setSampleSet(SampleSet sset) {
        this.sset = sset;
        sList.setListData(sset.getSet());
    }

    public Sample getSelectedSample() {
        return (Sample) sList.getSelectedValue();
    }

    public void removeSample(Sample sample) {
        sset.removeSample(sample);
        sList.setListData(sset.getSet());
    }

    private String getTitle() {
        if (sset != null) {
            return sset.toString();
        } else {
            return "<No Sample Set>";
        }
    }

    public void addSample(Sample sample) {
        sset.addSample(sample);
        sList.setListData(sset.getSet());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sList = new javax.swing.JList();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Sample Set"));
        setMinimumSize(new java.awt.Dimension(300, 200));
        setPreferredSize(new java.awt.Dimension(300, 269));
        setLayout(new java.awt.BorderLayout());

        sList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(sList);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList sList;
    // End of variables declaration//GEN-END:variables

}
